### ISSUE TITLE
Is it really for a local use ? (no internet)

### ISSUE THREAD

**Issue by jpggithub** [center-key/reveal.js-local#1]
Hi
I don't understand what "local" mean here?
Without connexion, only a simple HTML page is displayed.
Please, can you explain the purpose of your "local" solution?

EDIT: There is some CDN links in your file, it's not local files.

**Comment by pilafmon** [comment]
Are you doing academic research?  If you let me know what your objective is, I can probably help you out more easily.

**Comment by jpggithub** [comment]
Not at all, I just don't understand or misunderstand the meaning of the word "local" in this context (I'm not a good english speaker).
I want to run revealjs slides without internet connexion and thought that reveal-js-local could help me. It is not the case.

**Comment by pilafmon** [comment]
You can download all the CDN files to a subfolder of your presentation and load the files from the subfolder.  Once you have downloaded `presentation-template.html` and saved it locally, add a subfolder called `cdn`.

Then download the following 16 files into your new `cdn` folder:

   * https://center-key.github.io/reveal.js-local/assets/bookmark.png
   * https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@6.4/css/all.min.css
   * https://cdn.jsdelivr.net/npm/dna-engine@3.0/dist/dna-engine.css
   * https://cdn.jsdelivr.net/npm/dna-engine@3.0/dist/panel-nav.css
   * https://cdn.jsdelivr.net/npm/reveal.js@5.0/dist/reveal.css
   * https://cdn.jsdelivr.net/npm/hljs-enhance@2.0/hljs-enhance.css
   * https://cdn.jsdelivr.net/gh/center-key/reveal.js-local@0.3/docs/reveal.js-local.css
   * https://cdn.jsdelivr.net/npm/reveal.js@5.0/dist/reveal.js
   * https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@11.9/build/highlight.min.js
   * https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@11.9/build/languages/http.min.js
   * https://cdn.jsdelivr.net/npm/dna-engine@3.0/dist/dna-engine.min.js
   * https://cdn.jsdelivr.net/npm/hljs-enhance@2.0/hljs-enhance.js
   * https://cdn.jsdelivr.net/gh/center-key/reveal.js-local@0.3/docs/reveal.js-local.js
   * https://cdn.jsdelivr.net/npm/chart.js@4.4/dist/chart.umd.js
   * https://cdn.jsdelivr.net/npm/chartjs-plugin-datalabels@2.2/dist/chartjs-plugin-datalabels.min.js
   * https://cdn.jsdelivr.net/npm/chartjs-plugin-annotation@3.0/dist/chartjs-plugin-annotation.min.js

Now in the `presentation-template.html` file replace the following 16 lines:

```html
      <link rel=icon       href=https://center-key.github.io/reveal.js-local/assets/bookmark.png>
      <link rel=stylesheet href=https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@6.4/css/all.min.css>
      <link rel=stylesheet href=https://cdn.jsdelivr.net/npm/dna-engine@3.0/dist/dna-engine.css>
      <link rel=stylesheet href=https://cdn.jsdelivr.net/npm/dna-engine@3.0/dist/panel-nav.css>
      <link rel=stylesheet href=https://cdn.jsdelivr.net/npm/reveal.js@5.0/dist/reveal.css>
      <link rel=stylesheet href=https://cdn.jsdelivr.net/npm/hljs-enhance@2.0/hljs-enhance.css>
      <link rel=stylesheet href=https://cdn.jsdelivr.net/gh/center-key/reveal.js-local@0.3/docs/reveal.js-local.css>
      <script defer src=https://cdn.jsdelivr.net/npm/reveal.js@5.0/dist/reveal.js></script>
      <script defer src=https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@11.9/build/highlight.min.js></script>
      <script defer src=https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@11.9/build/languages/http.min.js></script>
      <script defer src=https://cdn.jsdelivr.net/npm/dna-engine@3.0/dist/dna-engine.min.js></script>
      <script defer src=https://cdn.jsdelivr.net/npm/hljs-enhance@2.0/hljs-enhance.js></script>
      <script defer src=https://cdn.jsdelivr.net/gh/center-key/reveal.js-local@0.3/docs/reveal.js-local.js></script>
      <script src=https://cdn.jsdelivr.net/npm/chart.js@4.4/dist/chart.umd.js></script>  <!-- wait for loading -->
      <script src=https://cdn.jsdelivr.net/npm/chartjs-plugin-datalabels@2.2/dist/chartjs-plugin-datalabels.min.js></script>  <!-- wait for loading -->
      <script src=https://cdn.jsdelivr.net/npm/chartjs-plugin-annotation@3.0/dist/chartjs-plugin-annotation.min.js></script>  <!-- wait for loading -->
```
With these 16 lines:
```html
      <link rel=icon       href=cdn/bookmark.png>
      <link rel=stylesheet href=cdn/all.min.css>
      <link rel=stylesheet href=cdn/dna-engine.css>
      <link rel=stylesheet href=cdn/panel-nav.css>
      <link rel=stylesheet href=cdn/reveal.css>
      <link rel=stylesheet href=cdn/hljs-enhance.css>
      <link rel=stylesheet href=cdn/reveal.js-local.css>
      <script defer src=cdn/reveal.js></script>
      <script defer src=cdn/highlight.min.js></script>
      <script defer src=cdn/http.min.js></script>
      <script defer src=cdn/dna-engine.min.js></script>
      <script defer src=cdn/hljs-enhance.js></script>
      <script defer src=cdn/reveal.js-local.js></script>
      <script src=cdn/chart.umd.js></script>  <!-- wait for loading -->
      <script src=cdn/chartjs-plugin-datalabels.min.js></script>  <!-- wait for loading -->
      <script src=cdn/chartjs-plugin-annotation.min.js></script>  <!-- wait for loading -->
```

**Comment by jpggithub** [comment]
Thank you!
By the way, you could add these information on the README.md.
